#!/bin/zsh

set -e


#####################
###   ARGUMENTS   ###
#####################

RESTORE_PATH=$1
TARGET_PATH=$2

#####################
### CONFIGURATION ###
#####################

# Get Backblaze B2 credentials and variables
B2_ACCOUNT=$(secret-tool lookup backblaze app-key-id)
B2_KEY=$(secret-tool lookup backblaze app-key)
B2_BUCKET=$(secret-tool lookup backblaze backup-bucket)
B2_DIR="backups/home"

# GPG Key for Encryption and Signing
# Public key IDs (last eight characters)
ENC_KEY_ID=$(secret-tool lookup key backup-encryption-key-id)
SGN_KEY_ID=$(secret-tool lookup key backup-signing-key-id)
export PASSPHRASE=$(secret-tool lookup key backup-encryption-key-passphrase)
export SIGN_PASSPHRASE=$(secret-tool lookup key backup-signing-key-passphrase)

#####################
###    SCRIPT     ###
#####################

# Check parent directory exists for target and also whether we will be
# overwriting files.
if [ ! -d $(dirname ${TARGET_PATH}) ]; then
  echo "Parent directory of target ${TARGET_PATH} does not exist, aborting..."
  exit -101
fi

if [ -e ${TARGET_PATH} ]; then
  echo "Target directory ${TARGET_PATH} exists, press CTRL-C now to cancel if you do not wish to overwrite..."
  sleep 2
  echo "Continuing to overwrite ${TARGET_PATH} with new files..."
fi

B2_URL="b2://${B2_ACCOUNT}:${B2_KEY}@${B2_BUCKET}/${B2_DIR}"

echo "Restoring files from ${RESTORE_PATH} to ${TARGET_PATH}"

duplicity restore \
  --sign-key ${SGN_KEY_ID} --encrypt-key ${ENC_KEY_ID} \
  --file-to-restore ${RESTORE_PATH} \
  "${B2_URL}" "${TARGET_PATH}"
