#
# export paths
#
# Executables from node modules
export PATH="./node_modules/.bin:$PATH"
# Compose executables
export PATH="~/.composer/vendor/bin:$PATH"
# Homebrew on the path
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
# Yarn
export PATH="$HOME/.yarn/bin:$PATH"
# Rust
export PATH="$HOME/.cargo/bin:$PATH"
# Local bin (e.g. haskell)
export PATH="$HOME/.local/bin:$PATH"

# Stop pyenv adding things to the prompt
export VIRTUAL_ENV_DISABLE_PROMPT="yes"
