zsh_dotfile_path=$(dirname $(readlink $HOME/.zshrc))
fpath=($zsh_dotfile_path/zsh/completion $fpath)

# waiting dots
COMPLETION_WAITING_DOTS="true"

# VI-mode
bindkey -v
export KEYTIMEOUT=1 # nb can cause problems with other scripts

# autocompletes
autoload -U compinit
compinit

# Glob-like autocomplete
setopt glob_complete
setopt no_case_glob

# history
setopt append_history
setopt share_history
setopt hist_ignore_dups
function zshaddhistory() {
    emulate -L zsh
    # don't store journal entries in history
    if ! [[ "$1" =~ "^jrnl" ]]; then
        print -sr -- "${1%%$'\n'}"
        fc -p
    else
        return 1
    fi
}

# Change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE
HOSTNAME="`hostname`"

# allow VIM to use C-s as a mapping
stty -ixon

# source other things
source $zsh_dotfile_path/aliases
source $zsh_dotfile_path/exports
source $zsh_dotfile_path/functions
source $zsh_dotfile_path/prompt
source $zsh_dotfile_path/secrets

# Z
ZSH_PATH=`brew --prefix`/etc/profile.d/z.sh
[ -e $ZSH_PATH ] && . $ZSH_PATH

# Use fzf for shell things too
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Grep anywhere with ^G
bindkey -s '^G' ' | grep '

# Allow opening of command in $EDITOR
# see http://unix.stackexchange.com/a/6622
bindkey -M vicmd v edit-command-line
autoload edit-command-line
zle -N edit-command-line

# Plugins
source $zsh_dotfile_path/zsh/plugins/web_search.zsh
